### ISSUE TITLE
Update Calender Events

### ISSUE THREAD

**Issue by Blinningjr** [rpa-tomorrow/substorm-nlp#121]
# Summary
It would be nice if the user can update Calendar event so that they don't have to delete the old event and make a new one with the updated information.

# Examples
"Move meeting with Niklas to 15:00"
"Update meeting at 13:30 to start at 13:20"

# Context
The Requirement Specification has an example where the intent is to update calendar event. Thus it would be nice if that example worked.

**Comment by hugowangler** [comment]
Agreed, probably the next thing to work on for improving the schedule module.
