### ISSUE TITLE
Improve followup system in Automation lib

### ISSUE THREAD

**Issue by Aleman778** [rpa-tomorrow/substorm-nlp#158]
# Description
Currently, the followup system is centered around being executed in a command line, I suggest extending this idea of a followup string to a data structure that holds more information. You can still include a description in a string but maybe also provide what kind of input from the user is expected which can also be easily translated into GUI components, combo boxes, text fields etc.

Right now the followup system cannot be used more than displaying the followup string to the user and providing a text field for prompting an answer.

**Comment by markhakansson** [comment]
This would be useful for the CLI as well - to be able to format the followup input/output. 

Followup in all modules are already decoupled from the CLI but [here in the Automation class](https://github.com/rpa-tomorrow/substorm-nlp/blob/master/lib/automate/__init__.py#L79) there is a print and console input which should not be there, but handled externally by the interfaces instead. If somone want to do this issue, they should start there.

**Comment by widforss** [comment]
An object is returned in #169, but it doesn't consolidate input/output into interfaces yet.
