### ISSUE TITLE
Debloat the README

### ISSUE THREAD

**Issue by markhakansson** [rpa-tomorrow/substorm-nlp#162]
# Summary
The readme is too long for people like me (that can't concentrate for more than 5 minutes) to read. We should probably split certain longer sections and place them in a separate markdown file in `docs/` directory where we refer to them in the README itself. Keep the README as simple as possible and easier to find the sections one need.

# Examples
Google Setup -> `docs/GOOGLE.md`
etc.

# Context
n/a

**Comment by Aleman778** [comment]
You could also add a table of contents so you can easily find what you want to read.
