### ISSUE TITLE
GUI - unable to delete tasks via interface

### ISSUE THREAD

**Issue by viktorfrom** [rpa-tomorrow/substorm-nlp#205]
# Expected behavior
Create a new task, delete the task using the interface.

# Actual behavior
Task does not disappear when attempting to delete it.

# Steps to reproduce
1. Create a new task in the design view.
2. Attempt to delete the task.

**Comment by Aleman778** [comment]
Lol this works but you have to first select the task so it is outlined in blue and then it will be deleted, though this should be made more clear in the GUI.

**Comment by Aleman778** [comment]
Improved this by also selecting the task with right click, solved in #175
