### ISSUE TITLE
Custom Training Corpus

### ISSUE THREAD

**Issue by 97gushan** [rpa-tomorrow/substorm-nlp#40]
Create by generation or other ways a custom corpus with labels.   

Example sentences:
"send an email to john.doe@gmail.com that I want to meet him tomorrow."
"remind me in 2 hours that i need to go grab lunch."

**Comment by Aleman778** [comment]
This is something I have explored by using generators see:
[https://github.com/Aleman778/substorm-prestudy/blob/master/src/data_generation.py](https://github.com/Aleman778/substorm-prestudy/blob/master/src/data_generation.py)

This uses generators to create fake dataset, however this is very slow and is probably not a good solution.
