### ISSUE TITLE
Connect Email automation to gmail API

### ISSUE THREAD

**Issue by 97gushan** [rpa-tomorrow/substorm-nlp#45]
# Summary
Connect the email module to gmail and give the user a option to use it instead of a local SMTP server

[Link to Python example](https://developers.google.com/gmail/api/quickstart/python)

# Examples
- The user should be able to specify that all emails should go through the users gmail account
- The user should then be able to for example be able to input "send an email to john.doe@gmail.com and ask if the report is ready yet" and the email should be sent through the gmail account

# Context
The emails sent by our client must be connected to the users actual email account so that the user can see that an email has been sent when logged into their gmail service like Outlook or GMail. Thus we must give the option to use the gmail api for sending the messages. Future work will be to add other email services, for example Outlook.

**Comment by widforss** [comment]
We already have SMTP support, why should we add another protocol? Gmail have a SMTP-gateway.

**Comment by widforss** [comment]
See [my account setting](https://github.com/rpa-tomorrow/substorm-nlp/blob/master/lib/settings.py#L4) to see how to send via external account.

**Comment by 97gushan** [comment]
Did not know of the SMTP-gateway, my bad. Closing the issue

**Comment by widforss** [comment]
For Gmail it seems the hostname is smtp.gmail.com:465, using SSL.
