### ISSUE TITLE
Downloading models through the CLI

### ISSUE THREAD

**Issue by Aleman778** [rpa-tomorrow/substorm-nlp#65]
It would be nice to be able to download models from the _model-releases_ git repo and also the possibility to switch between models. If we decide to use Swedish model you could switch between Swedish and English. Also, this would be useful for testing different models by swapping and comparing them.

**Comment by banunkers** [comment]
I could take a look at this

**Comment by Blinningjr** [comment]
The switching models based on language was done in pr #107, but it requiers that the models are already installed and are in the `config/nlp_models` file.
