### ISSUE TITLE
Improve the handling of meeting participants in the schedule module

### ISSUE THREAD

**Issue by hugowangler** [rpa-tomorrow/substorm-nlp#74]
The `to` field is currently just presumed to be a list of emails in order for the user to just enter names we have to be able to extract the correct email for each specified meeting participant (if it is not an email).

In the beginning this can just be implemented by using fuzzy to determine the correct email corresponding to the name.

**Comment by banunkers** [comment]
Me and @Blinningjr is currently implementing this
