### ISSUE TITLE
Make it easier to change models used

### ISSUE THREAD

**Issue by markhakansson** [rpa-tomorrow/substorm-nlp#78]
# Summary
In the settings it should be easy to change the models used across the applications when e.g. changing language. Preferably in the settings. 

# Examples
Settings -> Set language -> Models are now updated 

# Context
Right now the models are hard-coded in the modules, it should be easier to change these when changing language or perhaps when changing to any other model.

**Comment by Aleman778** [comment]
Also make sure that the models are not reloaded every time an automation task is executed.
