### ISSUE TITLE
Set logging level as CLI flag

### ISSUE THREAD

**Issue by markhakansson** [rpa-tomorrow/substorm-nlp#85]
# Summary
When starting the program from the CLI flags to set the logging output should be supported to help during development and debugging.

# Examples
`python lib/cli/cli.py -d DEBUG`
`python lib/cli/cli.py -v #verbose output INFO?`

# Context
When logging in the application there should be an easy way to set the debug level. Could be done with plac.

**Comment by markhakansson** [comment]
As of #87 there is only a debug flag. Should consider if we need a verbose flag that enables INFO level output.

**Comment by hugowangler** [comment]
It would be nice if you were able to specify the lowest level you want to see logged i.e. `-d INFO` will show everything while `-d WARNING` will only display warnings and errors.

**Comment by markhakansson** [comment]
> It would be nice if you were able to specify the lowest level you want to see logged i.e. `-d INFO` will show everything while `-d WARNING` will only display warnings and errors.

Fix is available in #108
